apiVersion: v1
kind: Pod
metadata:
  name: gy-demo
  labels:
    app: gy-demo
spec:
  containers:
    - name: gy-demo-app
      image: ghcr.io/hykerman/gydemoapp:1.0
  imagePullSecrets:
  - name: secret/secretname
