apiVersion: v1
kind: Secret
metadata:
    name: backstage-pass
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:TWQhvzBlTc4=,iv:X6E5WAAQ0NclG2F+j6AFMwtQ7oEXB+zYaAfD7Uy8k5E=,tag:DfOuRAViEPRjnbwWIbO+rg==,type:str]
    password: ENC[AES256_GCM,data:IMxSKBAbBdHfUdFXrMAyGcym5/GjFPCLVdSj92wjdzyMPVcVUCrXTg==,iv:lTAMuQxxjNaXemcp2yRqYhp3QridhTa86zv2Z3dKd2A=,tag:UMZxIORxt5Z6+Olt72n6bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://gykeyvault1234.vault.azure.net
          name: sops-key
          version: 45f640d9d6bb4bfbabca7d1773188b83
          created_at: "2022-02-28T02:48:51Z"
          enc: tPlPkHJfoqC4Ip8yzUr7Il5_pZfJ0wvM-Uf7FWaduBlfhvo8pwXC8N94-4tHZLJDvnCt9gtuWnNoPeRyuof2aY7le83-0fEEy7TUoXb9n3m7S45cN34ZpXwH4Ce6j2F1Kz5vmprH9uyHagiETIyfhQZQB8jCTf404yoPLtb3OrJDXHeilqAEce0yiiQPbEhK_15Fh6GFrW5hkT5vGrhY9GuJBgoL2FyN2R5NpmWfZsX9ty4g0KHahd6YXYfSPMYOMYFtUi2yv-0K6MSI7pw8h3kEsLGAdOb-WAU3JhaLQx_GXcZKNnzgPpErnyr8qU--Zv7jGUZfduOFlPVZbQfIgA
    hc_vault: []
    age: []
    lastmodified: "2022-02-28T02:48:52Z"
    mac: ENC[AES256_GCM,data:JOnt87I7IQ7yLfSi7899ttcGKxP6hPxWd5f+4T6+eAVSgj1n8gVAuPSqPowS++pcSLARwm64Px10oG4nJGzDMj0p5HzaCYovdGY6ena/q/J7pOcvFOzCIcc+O4YRTR9+QNfhv8jxQvymDC0csVxU5uFhof9Pak4wt00+HKb0Q58=,iv:ubtX1lCmsRQJDp2tYWE2sfFYiEVgoDvNa0rHa73NtnE=,tag:tlITzfxsmYmGqD+L4E6Cig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
