apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:wUeQWNtqE94a4pLb/T5Xlvm1Hvpv6heLJ3d1iOmOGu/teA5ibYotW+5O+GJGlI1C/ddkuUIIg/NOJzkfL0+hHCRiHemjPeNwDxJ/IAlLO2k70iF3h1skfe/ApiMmEI4F+L9YF5SXVexPogATfnydTq6XYrBLHMjxFkPaKaH5hz9rugZ2XBA94+tltZNfTuuweO1uCIt71kFxpEJok8D035R1Wi0QMRwiwO/wbnADHCvC2MuDbSUxlEUS9ZyapYurcI7oMKK6fHOAeTt1IjDBhpPi6av1jjq7UA16+3zMX3tDGalowvD4AUiiO5QtofdmadnxAozFmm3ytN1jCM8Xoavw4lz7ER+RUblyYNZJ5IevrFCv53nuyw==,iv:+KHk6B+e68+3Np+sdAO8SPPYOL7nJcLfSPcohqL8HOg=,tag:9EMc18JhZqgsvUJNih3x/g==,type:str]
kind: Secret
metadata:
    name: backstage-pass
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://gykeyvault1234.vault.azure.net
          name: sops-key
          version: 45f640d9d6bb4bfbabca7d1773188b83
          created_at: "2022-03-04T02:31:29Z"
          enc: tJbqofNuYkkyxEpBDS6EbCI1vWCPlMKM9tEsfLtdLxZDIy94KFs0UJX_WuieRe2GhUgWQ7JH8XvF6I4_2bQrkPZPL2_lpxrMX7uSOZsdq3Tl7Y0RgIRpHg_1P0H1tKTKemrz_kcV_A3nEdfdpRUxPJqX5goDuuXr46XE_RsDEqbUhBoyv3fz6YiMrCgrtF8EJjWZxrVRHofMXbGwr0AkbFuJPK4HtDfskJ1r1gkTS0X0v7kRAJdbz3USz3E8geXsI6pDSDRqi2K-S3jVkV6WUdjqpUaoW5iXPT8-W1dM3dDWRiAFWhS45NF6xz0dKozNg15DUO0QaAlO-DssM-YbnQ
    hc_vault: []
    age: []
    lastmodified: "2022-03-04T02:31:30Z"
    mac: ENC[AES256_GCM,data:/JJeg6Iz7oqXInTtOtRlfdTH2BPM48RS4IHmYV2pnQQ6Y5KxOX48JGfadd73DQ95cPnUbWJA+CV98Fmwse+cJvMbAEXs6d9nYSa3A5k1ORrlvIawZOuwdKvWufCASBJLhbIAmwzChBpu7lFGeUmp5aShCS/WbBM8Oa7zv6UGLIY=,iv:cWmLnObhGYxjyViYNxEUP3kFTX6I6yXAhYNc4wZdKis=,tag:RW3EvICgVygEn0+zpsX+XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|\.dockerconfigjson)$
    version: 3.7.1
