apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:61Cb4zMreujhnShw3gROF4y/VsNdbYVMYZUf5SmDdyzVFIFkCrMQWM0vmDbjiavaWXVDShhmOfUNhqIkuY2lL9eLJWIg04ZddclEMlirz9JlxrUmP6i2zEbx9/FNwTpwoNukjRiYl8MTW+/CQzQ2fkejK8aMY73wSU4uJEHiggKMFwdr42rE5Rto1nSblGBxVx3aiMVjykQm658l9d2H8/U6Kt2RbYXBFw7jXs+/lcSYi/KGEKa+RzZ34ATRFI/T+jLMC4mPyKoYVavPqCLUF+yP+vtmmjjtFhcXekBDIMRato0XuKmoh4QvAjsRsrd439qm7duFAstr9GSWgOCOMHEz2Zy35YNv/wDHJpnZJVRsDLasIgjSpw==,iv:jp7Sqpy1CfCRJsem5tN522I64UyfFzhxg9IXvAB8/Eg=,tag:HU8ShkEfHRJQZgA4PHVGcg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: backstage-pass
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://gykeyvault1234.vault.azure.net
          name: sops-key
          version: 45f640d9d6bb4bfbabca7d1773188b83
          created_at: "2022-03-09T15:28:44Z"
          enc: clyndIEP2S-CVZ8zCbUjO8Xl1pwKRj4ww7ejNFVvbY1-CDM7zN5QVJ5uF740nSYlkyf4sZDSqCQabSwm6d_X262sEudjPJklMHsm8JQZK2y_kjsczJjJOzi2GWRc-3sKjiLF_wOhGdEmGsjDLQ2c24PKE9tonnGNPiNJ4STKlVTFMbw7kXlJgqvVxvG1D0aAGaJx5AWBeFcyAFEY9GZOziHB3X__DC4Yzj3ZNPme2GTi8AtbID4BXsLH5altfAqGTpIi15jQ4W-T0D2pzuJPu3aXmaAruYDPhvbkfNZ5wJEvKH7Kv_6aaYjpVuXGT5lTx8ItbR5y3gw6Ee4XE_2i1A
    hc_vault: []
    age: []
    lastmodified: "2022-03-09T15:28:45Z"
    mac: ENC[AES256_GCM,data:Q9t3z5IW5Gma2JyuuqgU96NCk1TuB6N3cItq+0HksB4/Al/tqvdbEJsjO4dAIh7xKPQTbeSICinutrGjtMAtc1z1+h0DGw4nQ3/Ur1UmHrOz6wqOpTiT2CHiwbeeUNVU7RWAfqKjlx5Bf29TUFxZ3jH0xdDED/uj4tfogHmLjnw=,iv:oRY6lsPmemoMfjrybpQlMlysvJFsnWbSrisiy1BNfZY=,tag:IXoSMOQshgKySstsqofIdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|\.dockerconfigjson)$
    version: 3.7.1
